name: Check Android PR

on:
  pull_request:
    paths:
      - 'android/**'
      - 'lib/**'
      - 'lang/**'
      - 'fonts/**'
      - 'pubspec*'
      - 'pigeons/**'
      - 'test/**'
      - '.github/workflows/pull-android.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: dart-lang/setup-dart@v1.3
      - run: dart pub global activate fvm
      - run: fvm install
      - run: fvm flutter pub get
      - run: fvm flutter analyze
        continue-on-error: true
      - name: Flutter test
        continue-on-error: true
        run: fvm flutter test
      - run: fvm flutter build apk --debug
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload golden failures
        uses: actions/upload-artifact@v1
        with:
          name: goldens-failures
          path: test/components/failures/
